defaults:
  - _self_

_target_: isaacgymenvs.model.transformer.PCDTransformer

# Model architecture parameters
hidden_dim: 128  # Token dimension / hidden dimension throughout the model
type_dim: 4  # Dimension for type embeddings
dropout: 0  # Dropout rate
chunk_size: ${chunk_size}  # Number of action tokens to output

normalize_state: ${normalize_state}
normalize_action: ${normalize_action}
action_std: 1 # provide action_std for relative or delta action space
action_space: ${action_space}
action_dim: 32  # Glorbot (3+7+4*4+6)

# Point cloud encoder parameters
pcd_encoders_cfg:
  # Note this is just for reference, not all obs are used at the same time
  # initial frame obs
  static_scene_pcd_t0:
    type: "pointnet"  # Options: ["mlp", "pointnet"]
    num_output_tokens: 48  # Number of tokens for scene point cloud
    num_points: 1024
    use_pcd: true
  object_pcd_t0:
    type: "pointnet"  # Options: ["mlp", "pointnet"]
    num_output_tokens: 16  # Number of tokens for robot point cloud
    num_points: 256
    use_pcd: true
  # full_scene_pcd_t0:
  #   type: "pointnet"  # Options: ["mlp", "pointnet"]
  #   num_output_tokens: 128 # 32 Number of tokens for target point cloud
  #   use_pcd: true

  # full scene pcd
  # full_scene_pcd_t:
  #   type: "pointnet"  # Options: ["mlp", "pointnet"]
  #   num_output_tokens: 128 # Number of tokens for target point cloud
  #   use_pcd: true

  # full pcd (static obstacles + object + robot)
  # full_pcd_t:
  #   type: "pointnet"  # Options: ["mlp", "pointnet"]
  #   num_output_tokens: 64 # Number of tokens for target point cloud
  #   num_points: 1024
  #   use_pcd: true

  # # robot pcd obs
  # robot_pcd_t:
  #   type: "pointnet"  # Options: ["mlp", "pointnet"]
  #   num_output_tokens: 32  # Number of tokens for robot point cloud
  #   use_pcd: true
  # hand_pcd_t:
  #   type: "pointnet"  # Options: ["mlp", "pointnet"]
  #   num_output_tokens: 32  # Number of tokens for robot point cloud
  #   use_pcd: true

  # # local pcd
  local_pcd_t:
    type: "pointnet"  # Options: ["mlp", "pointnet"]
    num_output_tokens: 64  # Number of tokens for target point cloud
    num_points: [1024, 1024] # cylindrical local pcd + spherical eef local pcd
    use_pcd: true
  # local_scene_pcd_t:
  #   type: "pointnet"  # Options: ["mlp", "pointnet"]
  #   num_output_tokens: 32  # Number of tokens for target point cloud
  #   use_pcd: true

# State encoders (MLP parameters)
state_encoders_cfg:
  q_arm_manip:
    input_dim: 7
    hidden_dims: [128, 256]
    dropout: 0
    use_state: true
  q_arm_vision:
    input_dim: 6
    hidden_dims: [128, 256]
    dropout: 0
    use_state: true
  q_hand:
    input_dim: 16
    hidden_dims: [128, 256]
    dropout: 0
    use_state: true
  q_hand_ctrl_delta:
    input_dim: 16
    hidden_dims: [128, 256]
    dropout: 0
    use_state: true
  # current_angles:
  #   input_dim: 7
  #   hidden_dims: [128, 256]
  #   dropout: 0
  #   use_state: true
  # goal_angles:
  #   input_dim: 7
  #   hidden_dims: [128, 256]
  #   dropout: 0
  #   use_state: true
  # delta_angles:
  #   input_dim: 7
  #   hidden_dims: [128, 256]
  #   dropout: 0
  #   use_state: true

# Transformer parameters
transformer_cfg:
  type: "encoder_decoder"  # Options: ["encoder_decoder"]
  encoder_layers: 6  # Number of encoder layers
  decoder_layers: 6  # Number of decoder layers
  encoder_heads: 8  # Number of encoder attention heads
  decoder_heads: 8  # Number of decoder attention heads
  encoder_dim_feedforward: 1024  # Dimension of encoder feedforward network
  decoder_dim_feedforward: 1024  # Dimension of decoder feedforward network