defaults:
  - _self_

_target_: isaacgymenvs.model.transformer.PCDTransformer

hidden_dim: 128
type_dim: 4
dropout: 0
chunk_size: ${chunk_size}

normalize_state: ${normalize_state}
normalize_action: ${normalize_action}
action_std: 1
action_space: ${action_space}
action_dim: 32
aux_weight: 0.1
aux_prediction_mode: "delta"
aux_delta_scale: 0.01

pcd_encoders_cfg:
  local_pcd_t:
    type: "pointnet"
    num_output_tokens: 128
    num_points: [2048, 0, 1024]
    use_pcd: true

state_encoders_cfg:
  q_arm_manip:
    input_dim: 7
    hidden_dims: [128, 256]
    dropout: 0
    use_state: true
  q_arm_vision:
    input_dim: 6
    hidden_dims: [128, 256]
    dropout: 0
    use_state: true
  q_hand:
    input_dim: 16
    hidden_dims: [128, 256]
    dropout: 0
    use_state: true
  q_hand_ctrl_delta:
    input_dim: 32
    hidden_dims: [128, 256]
    dropout: 0
    use_state: true
  aux_object_state:
    input_dim: 3
    hidden_dims: [128, 256]
    dropout: 0
    use_state: true

transformer_cfg:
  type: "encoder_decoder"
  encoder_layers: 6
  decoder_layers: 6
  encoder_heads: 8
  decoder_heads: 8
  encoder_dim_feedforward: 1024
  decoder_dim_feedforward: 1024
