

goal_blocker:
  enable: True
  num: 1
  size:
    low: [0.1, 0.1, 0.1]
    high: [0.2, 0.2, 0.2]


quasi_dynamic:
  enable: False
  num: 2
  size:
    low: [0.1, 0.1, 0.1]
    high: [0.3, 0.3, 0.3]


floating:
  enable: True
  num: 5
  size:
    low: [0.1, 0.1, 0.1]
    high: [0.3, 0.3, 0.3]
